# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20160211_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('from_user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='user.UserProfile')),
            ],
        ),
    ]
