# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conversation.Conversation'),
            preserve_default=False,
        ),
    ]
