# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_to_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 16, 9, 53, 23, 897412, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
