# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation.Relation'),
        ),
    ]
