# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('message', '0004_auto_20160216_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='relation.Relation'),
        ),
    ]
