# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20160301_0845'),
        ('message', '0006_auto_20160229_1459'),
    ]

    operations = [
    ]
