# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
