# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_auto_20160301_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='relation.Relation'),
        ),
    ]
