# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import message.models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_auto_20160301_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='associated_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=message.models.message_directory_path),
        ),
    ]
