# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 09:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 3, 1, 9, 3, 20, 24483, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sport.Sport'),
        ),
    ]
