# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20160301_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='user.UserProfile'),
        ),
    ]
