# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_userprofile_picture'),
        ('group', '0004_auto_20160302_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ADM', 'Admin'), ('MEM', 'Member'), ('PEN', 'Pending')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='groupstatus',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group'),
        ),
        migrations.AddField(
            model_name='groupstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='groupstatus',
            unique_together=set([('group', 'user')]),
        ),
    ]
