# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_auto_20160308_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.IntegerField(default=1),
        ),
    ]
