# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_coach', to='user.UserProfile')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_trainee', to='user.UserProfile')),
            ],
        ),
    ]
