# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
        ('relation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='relation',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 2, 13, 15, 36, 28, 894452, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='requestStatus',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='relation',
            name='sport',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sport.Sport'),
            preserve_default=False,
        ),
    ]
