# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_auto_20160213_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='relationIsActive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
