# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0005_auto_20160301_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
