# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0006_relation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='requestStatus',
            field=models.NullBooleanField(default=None),
        ),
    ]
