# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='device',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='device',
            name='reg_id',
        ),
        migrations.AddField(
            model_name='device',
            name='reg_token',
            field=models.CharField(default='lol', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
