# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20160304_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='dev_id',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='reg_token',
            new_name='registration_token',
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('user', 'device_id')]),
        ),
    ]
