# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20160304_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='registration_token',
            field=models.CharField(max_length=255),
        ),
    ]
