# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-10 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('coachs', models.ManyToManyField(related_name='userprofile_coachs', to='user.UserProfile')),
                ('levels', models.ManyToManyField(to='level.Level')),
                ('trainees', models.ManyToManyField(related_name='userprofile_trainees', to='user.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
