# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coachs',
            field=models.ManyToManyField(blank=True, related_name='userprofile_coachs', to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='levels',
            field=models.ManyToManyField(blank=True, to='level.Level'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='trainees',
            field=models.ManyToManyField(blank=True, related_name='userprofile_trainees', to='user.UserProfile'),
        ),
    ]
