# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='coachs',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='trainees',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
