# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160215_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=user.models.user_directory_path),
        ),
    ]
